### ISSUE TITLE
linea del tiempo

### ISSUE THREAD

**Issue by PedroGarcia11439** [SistemasTecTlaxiaco/actividad-7-PedroGarcia11439#1]
[Evolución de las web's.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-PedroGarcia11439/files/9801335/Evolucion.de.las.web.s.pdf)

**Comment by josealfredo79** [comment]
Calificacion 15

**Comment by josealfredo79** [comment]
Hacen falta mas diseño y varias fechas importantes

**Comment by josealfredo79** [comment]
Revisado...
